#%RAML 1.0
title: author-sys-api
/getAuthorDetails:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "AuthorName" : "Kalyan"
              }